finished authorization with pundit
RJDPI/industrial-auth-1 pull request #2
Opened 2023-11-11 08:56 UTC by RJDPI

2023-11-12 19:35 UTC, Samuel-Lubliner requested changes
When I sign in as Alice and try to view the user profile `/alice` I get the error Sprockets::Rails::Helper::AssetNotFound at /alice
The asset "." is not present in the asset pipeline.

2023-11-12 21:31 UTC, ghost commented
/alice etal happening.

2023-11-12 21:31 UTC, closed without merging

2023-11-17 16:21 UTC, heratyian commented on app/controllers/comments_controller.rb
> +  # def ensure_current_user_is_author
You can delete this commented out code

2023-11-17 16:21 UTC, heratyian commented on app/controllers/follow_requests_controller.rb
> +  # def index
same here. better to just delete

2023-11-17 16:22 UTC, heratyian reviewed
Remember to delete commented out code. Can always recover later in git commit history.